###
POST http://localhost:8000/api/signup
Content-Type: application/json

{
  "name": "Kumary",
  "email": "kumaryniks@gmail.com",
  "password": "kumary123"
}

###correct credentials
POST http://localhost:8000/api/signin
Content-Type: application/json

{
  "email": "fyugma@gmail.com",
  "password": "yugma123"
}

###incorrect credentials

POST http://localhost:8000/api/signin
Content-Type: application/json
//correct credentials
{
  "email": "kumaryniks@gmail.com",
  "password": "kumary12"
}

###signout
GET http://localhost:8000/api/signout

###
