###
GET http://localhost:8000/api/5e626a9b0a936a1b2009628d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTYyNmE5YjBhOTM2YTFiMjAwOTYyOGQiLCJpYXQiOjE1ODM2MTAwNTF9.gwUvn8Sn21lW0AdgbojvAsCdppOTH0zO6EF-Lj9RK3E

###

